### ISSUE TITLE
Hangs

### ISSUE THREAD

**Issue by clairestreb** [countnazgul/QS-backup-and-restore-app#14]
I downloaded the extension.  I imported it to the server.  It said it was invalid but loaded it anyway.  I opened up the extension in the mashup editor.  I selected a qvf, and clicked open.  It opened.  I clidked the Backup button, and it just spins and never does anything.

![backup-and-restore-hangs](https://cloud.githubusercontent.com/assets/3613890/24379257/48005e8a-1314-11e7-8fed-2d86f023d537.png)

I unzipped into and placed it in the Desktop's Extension folder.  The same thing happens.

I placed an alert in backup-and-restore.js on line 494 right after   $("#serialize").on("click", function () {
The alert never pops up.

I have a suspicion that there is either a conflict, or the "require" statement on line 21 is not working, or some other dependency has not been fulfilled.

Someone else I was working with had an old version of the extension.  He isn't having any problems on his Desktop.  He zipped it up and gave it to me, and the same thing happened, both on my Desktop and the server.  I am also posting this on Alexander's page.

I am running with Qlik Sense 3.2 SR1 and Desktop 3.1 SR4.

**Comment by lennartq** [comment]
It looks like a bug in 0.10.1. Try using 0.10 or, in the file serialize.bundle.js, before the row

function serializeApp(app, callback) {

add

serializeAppBundle =

The 0.10.0 version has
serializeAppBundle =
function serializeApp(app, callback) {

and both versions call serializeAppBundle in backup-and-restore.js

**Comment by clairestreb** [comment]
Works, but see other Restore hang issue
