### ISSUE TITLE
Restore not working

### ISSUE THREAD

**Issue by Kielland** [countnazgul/QS-backup-and-restore-app#7]
Hi

This is an essential extension! But I cannot get it to work :-) I'm using Qlik Sense Server 3.0.

I have been able to restore a tiny app with almost no content. But for apps with more content, the green spinner just continues forever when it tries to restore.

Also, I notice that the "Restore" button is only enabled when I have opened the the same app that I'm attempting to restore, using the open button in the user interface. This makes sense, because it stops people from restoring one app onto a different app. However, is it possible to handle the scenario where I want to restore an app that I don't have. (E.g. I have accidentally deleted it.) I did try to create a completely empty app, and restore an existing app onto it. (The Restore button allowed this.) However, I don't know whether it's working, since I cannot restore apps at all.

Thanks a lot for your feedback!
Tor

**Comment by countnazgul** [comment]
Thanks for your feedback Tor. 
I was planning to make changes in the app in the next few days (actually started them in the development branch). Few of the changes will address the issues you are experiencing. After this you will be able to restore in empty app, the process will be more stable and indication of errors during the process. I've spotted cases with specific objects yesterday (like bookmarks and variables) where the process is failing but this result is - green spinner never ends.

**Comment by Kielland** [comment]
That's superb news. My initial thinking was that the process would perhaps be more stable if you always do a complete restore. But I guess there are technical reasons why you have chosen to delete/add/update single elements in the app.
Looking forward to the next version!
Tor

**Comment by Kielland** [comment]
Hey Stefan

Just checking in. Would be interested to hear if you expect to do the
updates in the nearest future. (For my own planning.)

Thanks!
Tor

---

Tor Kielland
BrightArch AS
Gaustadalleen 21
0349 Oslo, Norway
+47 - 977 94 414
tor@brightarch.com
www.brightarch.com

**Comment by lennartq** [comment]
I have the same problem - can't download anything. Does this work with Sense 3.0.x?
