### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by SandroK** [countnazgul/QS-backup-and-restore-app#9]
We had trouble importing from a json file with the Euro sign and our German Umlaute.

The change to the backup_and_restore.js, that anguilla recommended in the Qlik Branch http://branch-test.qlik.com/#!/project/56728f52d1e497241ae698c7 worked for us. Seem like a fix, that should be made permanent

**Comment by countnazgul** [comment]
Thanks Sandro. I've made the change and will be in the next version. 
Not sure why im not getting the branch notifications on commenting.
